branches:
  only:
  - inst4gram

cache:
  apt: true

addons:
  apt:
    packages:
      - texlive-publishers
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science

script:
- mkdir _build
- python texliveonfly.py manutencao.tex

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file_glob: true
  file: _build/**/*.pdf
  skip_cleanup: true
  on:
    branch: inst4gram