branches:
  only:
    - alfa
addons:
  apt:
    packages:
      - texlive-publishers
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science
      - latex-xcolor

cache:
  apt: true

script:
  - mkdir _build
  - python texliveonfly.py manutencao.tex

before_deploy:
  - git tag "v$(date +'%Y.%m.%d.%H%M')"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: 
    - ./_build/manutencao.pdf
  skip_cleanup: true
  on:
    branch: inst4gram