cache:
  apt: true

addons:
  apt:
    packages:
      - texlive-publishers
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science

script:
  - python texliveonfly.py manutencao.tex

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: "manutencao.pdf"
  skip_cleanup: true
  on:
    tags: true