cache:
  apt: true

addons:
  apt:
    packages:
      - texlive-full

script:
  - mkdir _build
  - python texliveonfly.py manutencao.tex
  - cd _build
  - cat manutencao.log
  - ls

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: 
    - ./_build/manutencao.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: inst4gram