branches:
  only:
  - inst4gram

cache:
  apt: true

# before_install:
# - sudo apt-get update 
# - sudo apt-get install texlive-publishers texlive-lang-portuguese texlive-latex-extra texlive-fonts-recommended texlive-science

addons:
  apt:
    packages:
      - texlive-publishers
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science

script:
- python texliveonfly.py manutencao.tex
- mkdir _build
- cp manutencao.tex _build/

before_deploy:
- git tag "v$(date +'%Y.%m.%d.%H%M')"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file:
  - ./_build/manutencao.pdf
  skip_cleanup: true
  on:
    branch: inst4gram