branches:
  only:
  - inst4gram

cache:
  apt: true

addons:
  apt:
    packages:
      - texlive-publishers
      - texlive-lang-portuguese
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-science

script:
- mkdir _build
- python texliveonfly.py manutencao.tex

before_deploy:
- git config --local user.name "travis-ci"
- git config --local user.email "bot@travis-ci.org"
- git tag "v$(date +'%Y.%m.%d.%H%M')"

deploy:
  provider: releases
  api_key: $GIT_TOKEN
  file: _build/manutencao.pdf
  skip_cleanup: true
  on:
    tags: true